"""`litkb export tracker` / `litkb export manifest` — the CSV and xlsx twins, regenerated from the database.

Design §10: "`manifest.csv`, `Literature_Tracker.xlsx`, `literature_tracker.csv` → exports. Generated by
`litkb export`; never edited by hand." From P3 on, the database is authoritative and these files are its
printed view. Nothing here writes to the database.

**The view.** A workstream sees its own versions where it has them and main's everywhere else (`ws_works`,
`ws_identifiers`, `ws_files`, `ws_uses`, filtered on `view_workstream_id`). With no `--workstream` the export
is main's view alone, which is what a promoted, merged tracker will look like. P3's gate exports the
`p3-migration` workstream's view, because that is where P3's admissions live until Kam promotes them.

**Rows with no work.** A legacy row that is HELD — no verified file, or no resolvable identity — has no work
to print. It is exported from its candidate's `raw_record`, verbatim, with `Status` left exactly as the
tracker had it, so the export never silently loses a row. Its `litkb_state` column says why.

**What differs from today's files, and why that is the gate.** Identity fields come from the REGISTRY record
(decisions.yaml `litkb-p0-foundation`), not from the tracker's claim, so a row whose claim disagreed prints
the registry's title/authors/year/journal. Every such difference has a `discrepancies` row naming both
values: that pairing IS the reviewed diff (`litkb export tracker --diff`).
"""
import csv
import json
from pathlib import Path

from litkb.migrate_legacy import sources

TRACKER_EXPORT_COLUMNS = [*sources.TRACKER_COLUMNS, "litkb_key", "litkb_state"]
MANIFEST_EXPORT_COLUMNS = [*sources.MANIFEST_COLUMNS, "litkb_key", "litkb_legacy_stem", "litkb_state"]

_ROWS_SQL = """
SELECT cd.id, cd.source_detail, cd.state, cd.raw_record, cd.admitted_work_id, w.key,
       wv.title, wv.authors, wv.year, wv.venue
  FROM litkb.candidates cd
  LEFT JOIN litkb.works w ON w.id = cd.admitted_work_id
  LEFT JOIN litkb.ws_works wv ON wv.work_id = cd.admitted_work_id
                             AND wv.view_workstream_id = %(ws)s
 WHERE cd.workstream_id = %(ws)s AND cd.source_detail LIKE %(prefix)s
 ORDER BY cd.id
"""


def _authors_line(authors):
    """One home: `migrate_legacy.export_shape.authors_line`, which the loader's comparison also reads."""
    from litkb.migrate_legacy.export_shape import authors_line

    return authors_line(authors)


def _identifiers(conn, ws):
    """{work_id: {scheme: [values]}} in the workstream's view."""
    out = {}
    for work_id, scheme, value in conn.execute(
            "SELECT v.work_id, v.scheme, v.value FROM litkb.ws_identifiers v "
            "WHERE v.view_workstream_id = %s AND v.status = 'active'", (ws,)).fetchall():
        out.setdefault(work_id, {}).setdefault(scheme, []).append(value)
    return out


def _uses(conn, ws):
    """{work_id: use version} in the workstream's view — the tracker's Relevance / grade / Feeds."""
    out = {}
    for work_id, statement, feeds, confidence, rationale in conn.execute(
            "SELECT u.work_id, u.statement, u.feeds, u.confidence, u.rationale FROM litkb.ws_uses u "
            "WHERE u.view_workstream_id = %s AND u.status <> 'withdrawn' ORDER BY u.created_at", (ws,)).fetchall():
        out[work_id] = {"statement": statement, "feeds": list(feeds or []), "confidence": confidence,
                        "rationale": rationale}
    return out


def _files(conn, ws):
    """{work_id: file version} — the held file, for the manifest export."""
    out = {}
    for row in conn.execute(
            "SELECT f.work_id, f.sha256, f.rel_path, f.source_route, f.obtained_at, f.binding, f.status "
            "FROM litkb.ws_files f WHERE f.view_workstream_id = %s AND f.status = 'active'", (ws,)).fetchall():
        out[row[0]] = {"sha256": row[1], "rel_path": row[2], "source_route": row[3], "obtained_at": row[4],
                       "binding": row[5], "status": row[6]}
    return out


def _raw(rec):
    return rec if isinstance(rec, dict) else (json.loads(rec) if rec else {})


def tracker_rows(conn, ws):
    """The tracker, as the database now holds it. One row per loaded tracker row, in tracker ID order."""
    ids, uses = _identifiers(conn, ws), _uses(conn, ws)
    rows = []
    for _cid, detail, state, raw, work_id, key, title, authors, year, venue in conn.execute(
            _ROWS_SQL, {"ws": ws, "prefix": "tracker ID %"}).fetchall():
        r = _raw(raw)
        out = {c: r.get(c, "") for c in sources.TRACKER_COLUMNS}
        out["litkb_key"] = key or ""
        out["litkb_state"] = state or ""
        if work_id is not None:
            wid = ids.get(work_id, {})
            out["Title"] = title or out["Title"]
            out["Author(s)"] = _authors_line(authors) or out["Author(s)"]
            out["Year"] = str(year) if year else out["Year"]
            out["Journal/Source"] = venue or out["Journal/Source"]
            if wid.get("doi"):
                out["DOI/URL"] = f"https://doi.org/{wid['doi'][0]}"
            elif wid.get("arxiv"):
                out["DOI/URL"] = f"https://arxiv.org/abs/{wid['arxiv'][0]}"
            if wid.get("legacy_stem"):
                out["File stem"] = wid["legacy_stem"][0]
            # a `Duplicate of` row shares the original's WORK, so uses.get(work_id) would paint the
            # original's Relevance and Feeds onto it. The tracker keeps the payload on the original row only
            # (LITERATURE_CONVENTION.md), so the duplicate keeps its own words.
            u = uses.get(work_id) if not (r.get("Duplicate of") or "").strip() else None
            if u:
                # a use written for a row with no Relevance carries a placeholder statement (a use version's
                # `statement` may not be empty); the tracker cell it came from was blank and stays blank
                stmt = "" if str(u["statement"] or "").startswith("tracker row ") and                     u["statement"].endswith(": no relevance recorded") else u["statement"]
                out["Relevance (max 3 sentences)"] = stmt or out["Relevance (max 3 sentences)"]
                out["Feeds"] = "; ".join(u["feeds"]) or out["Feeds"]
                out["Evidence grade"] = u["confidence"] or out["Evidence grade"]
        rows.append(out)
    rows.sort(key=lambda x: int(x["ID"]) if str(x["ID"]).isdigit() else 10**9)
    return rows


def manifest_rows(conn, ws):
    """The manifest, as the database now holds it: one row per held file.

    Referee note M7: `works.key` is authoritative and `files.stem` is DERIVED from it. The export prints the
    key in `stem`; the LEGACY stem is printed too, in `litkb_legacy_stem`, because it is the only stable join
    between this file and the old manifest — the recorded sha256 is not (a row whose hash went stale is
    exactly the row a hash join would lose, and it is the row the review most needs to see).

    **A file the database refused is still printed.** A file that failed binding, or that waits for OCR
    (§15.14), has no work. Dropping it would delete a row from the manifest, so its legacy row is printed
    back verbatim with `litkb_state` saying what happened to it.
    """
    ids, files = _identifiers(conn, ws), _files(conn, ws)
    seen, rows = set(), []
    for _cid, detail, state, raw, work_id, key, title, authors, year, venue in conn.execute(
            _ROWS_SQL, {"ws": ws, "prefix": "%"}).fetchall():
        r = _raw(raw)
        # the manifest columns with no home in the data model travel on the candidate's raw_record, under
        # `_manifest` when the row entered through its TRACKER row (204 of the 207 did)
        mr = r.get("_manifest") or (r if "stem" in r else {})
        if not mr:
            continue                                   # a tracker row with no file: not a manifest row
        legacy = mr.get("stem") or ""
        if legacy in seen:
            continue
        seen.add(legacy)
        wid = ids.get(work_id, {}) if work_id else {}
        f = files.get(work_id) if work_id else None
        if f is None:
            # BEGIN guard: a refused file is still exported as a manifest row
            # held: no work, or a work whose file the database refused. The legacy row, unchanged.
            rows.append({**{c: mr.get(c, "") for c in sources.MANIFEST_COLUMNS},
                         "stem": key or legacy, "litkb_key": key or "", "litkb_legacy_stem": legacy,
                         "litkb_state": state or ""})
            continue
            # END guard: a refused file is still exported as a manifest row
        rows.append({
            "stem": key or legacy,
            "title": title or mr.get("title") or "",
            "authors": _authors_line(authors) or mr.get("authors") or "",
            "year": str(year) if year else (mr.get("year") or ""),
            "venue": venue or mr.get("venue") or "",
            "doi": (wid.get("doi") or [""])[0],
            "arxiv": (wid.get("arxiv") or [""])[0],
            "source_route": f["source_route"] or mr.get("source_route") or "in place (P3 migration)",
            "obtained_date": (str(f["obtained_at"])[:10] if f["obtained_at"] else mr.get("obtained_date") or ""),
            "sha256": f["sha256"] or mr.get("sha256") or "",
            # the binding check IS the verification the old column recorded by hand (convention rule 2)
            "verified_against_extract": "yes" if (f["binding"] or {}).get("verdict") == "bound" else "no",
            "cited_by": mr.get("cited_by") or "",
            "litkb_key": key or "",
            "litkb_legacy_stem": legacy,
            "litkb_state": state or "",
        })
    rows.sort(key=lambda x: x["stem"])
    return rows


def discrepancy_rows(conn, ws):
    return [dict(zip(("source", "source_row", "field", "claimed_value", "registry_value", "ratio", "work_key"), r))
            for r in conn.execute(
                "SELECT source, source_row, field, claimed_value, registry_value, ratio, work_key "
                "FROM litkb.discrepancy_report WHERE workstream_id = %s "
                "ORDER BY source, field, source_row", (ws,)).fetchall()]


def write_csv(path, columns, rows):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=columns, extrasaction="ignore")
        w.writeheader()
        for r in rows:
            # the CSV twins flatten newlines inside a cell to spaces (LITERATURE_CONVENTION.md)
            w.writerow({c: " ".join(str(r.get(c, "") or "").split()) for c in columns})
    return path


def write_xlsx(path, sheets):
    """`{sheet name: (columns, rows)}` -> one workbook. openpyxl only; skipped, never faked, if absent."""
    try:
        from openpyxl import Workbook
    except ImportError:
        return None
    wb = Workbook()
    wb.remove(wb.active)
    for name, (columns, rows) in sheets.items():
        sh = wb.create_sheet(name[:31])
        sh.append(list(columns))
        for r in rows:
            sh.append([" ".join(str(r.get(c, "") or "").split()) for c in columns])
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    wb.save(path)
    return path
