r"""colab_cli_vmgen.py — generate the VM-side scripts for a headless Colab CLI run
(overhaul P11.6).

The agentic GPU path runs Colab through Google's official `google-colab-cli`
(`colab new -s A --gpu A100`, `colab exec -s A -f <script>`), not through browser
tabs. Colab Secrets do not exist on CLI runtimes, so the private-repo clone needs
the GitHub token injected at SEND time: this generator reads it locally from
`gh auth token` and templates it into two scripts written to a LOCAL out dir
(the session scratchpad — never the repo, never Drive):

    vm_bootstrap.py   clone/update the repo at BRANCH (token scrubbed from
                      .git/config immediately), verify the Drive mount, ensure
                      phase4/logs + phase4/locks, pip install requirements,
                      print the GPU, dry-run the queue. Prints BOOTSTRAP_DONE.
    vm_launch.py      nohup the queue detached (survives the exec websocket
                      closing; dies only with the VM), log to
                      phase4/logs/train_queue_nohup_{queue}_{ts}.log, print pid
                      + log path + the first log lines.

Usage (local Windows; start the command with the literal `py -3.12` so the Bash
allow rule matches — a leading VAR=… assignment breaks rule matching):

    py -3.12 pipeline/colab_cli_vmgen.py --branch work/p11-5-autonomy \
        --queue queue_A_2024_2017.yaml --outdir <scratchpad>

Then, per the P11.6 runbook:
    colab new -s A --gpu A100                  (agent; first launch = Kam's yes)
    colab drivemount -s A                      (KAM, in his own terminal: URL ->
                                                approve -> Enter; once per VM)
    colab exec -s A -f <outdir>/vm_bootstrap.py --timeout 900
    colab exec -s A -f <outdir>/vm_launch.py   --timeout 60
    ... monitor Drive artifacts; colab status/log; colab stop -s A when done.

Crash recovery on a LIVE VM never needs a new drivemount: push the fix branch,
re-generate with --branch fix/..., re-run vm_bootstrap (it fetches + checkouts),
re-run vm_launch. Only a dead VM needs `colab new` + Kam's drivemount again.
"""
from phase4seg.names import clean_argv
import argparse
import pathlib
import subprocess
import sys

GH = r"C:/Program Files/GitHub CLI/gh.exe"
REPO_URL = "github.com/Kameron-Eck/edmonds-treedata.git"


def gh_token():
    t = subprocess.run([GH, "auth", "token"], capture_output=True, text=True).stdout.strip()
    if not t:
        sys.exit("no token from `gh auth token` — run `gh auth login` first")
    return t


BOOTSTRAP = '''# VM bootstrap (sent via `colab exec`; the token exists only in kernel memory
# and is scrubbed from .git/config in the same run). Auto-generated by
# pipeline/colab_cli_vmgen.py — do not commit.
import os, subprocess, sys
BRANCH = {branch!r}
REPO = "/content/repo"
AUTH = "https://x-access-token:{token}@{repo_url}"
CLEAN = "https://{repo_url}"
D = "/content/drive/MyDrive/treedata"
assert os.path.isdir(D), "Drive not mounted - run `colab drivemount` first (Kam's terminal)"
if os.path.exists(REPO):
    subprocess.run(["git", "-C", REPO, "remote", "set-url", "origin", AUTH], check=True)
    subprocess.run(["git", "-C", REPO, "fetch", "--depth", "1", "origin", BRANCH], check=True)
    subprocess.run(["git", "-C", REPO, "checkout", "-B", BRANCH, "FETCH_HEAD"], check=True)
else:
    subprocess.run(["git", "clone", "--depth", "1", "--branch", BRANCH, AUTH, REPO], check=True)
subprocess.run(["git", "-C", REPO, "remote", "set-url", "origin", CLEAN], check=True)  # scrub token
print("REPO", subprocess.run(["git", "-C", REPO, "rev-parse", "--abbrev-ref", "HEAD"],
                             capture_output=True, text=True).stdout.strip(),
      subprocess.run(["git", "-C", REPO, "log", "--oneline", "-1"],
                     capture_output=True, text=True).stdout.strip())
os.makedirs(D + "/phase4/logs", exist_ok=True)
os.makedirs(D + "/phase4/locks", exist_ok=True)   # P11.4: lock dir pre-exists
subprocess.run([sys.executable, "-m", "pip", "install", "-q", "-r",
                REPO + "/Scripts/requirements-colab.txt"], check=True)
try:
    import torch
    print("GPU:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "NONE")
except Exception as e:                                              # noqa: BLE001
    print("GPU check failed:", e)
r = subprocess.run([sys.executable, "phase4_train_queue.py", "--dry-run", "--queue", {queue!r}],
                   cwd=REPO + "/Scripts/pipeline", capture_output=True, text=True)
print(r.stdout[-900:])
print("BOOTSTRAP_DONE" if r.returncode == 0 else "DRYRUN_FAIL rc=%d" % r.returncode)
'''

LAUNCH = '''# VM launch: nohup the queue detached (survives the exec websocket; dies only
# with the VM). Auto-generated by pipeline/colab_cli_vmgen.py — do not commit.
import datetime, os, subprocess, time
Q = {queue!r}
ts = datetime.datetime.now(datetime.timezone.utc).strftime("%Y%m%dT%H%M%SZ")
log = "/content/drive/MyDrive/treedata/phase4/logs/train_queue_nohup_" + Q[:-5] + "_" + ts + ".log"
p = subprocess.Popen("cd /content/repo/Scripts/pipeline && nohup python -u phase4_train_queue.py "
                     "--queue " + Q + " > " + log + " 2>&1 & echo $!",
                     shell=True, stdout=subprocess.PIPE, text=True)
out, _ = p.communicate(timeout=30)
print("LAUNCHED pid", out.strip())
print("LOG", log)
time.sleep(8)
print("--- first log lines ---")
print(open(log).read()[:1200] if os.path.exists(log) else "(log not flushed yet - read it from Drive)")
'''


# ── QC mode (2026-08-24) ──────────────────────────────────────────────────────
# Same clone/Drive/pip bootstrap, but the readiness probe is a QC smoke instead of a
# queue dry-run, and the launch runs qc/imagery_qc_suite.py against the DRIVE copies.
# That is the point of running QC on a VM at all: locally the suite reads the fast D:
# originals, so a Colab pass over the data lake is an INDEPENDENT reading of the
# mirrored files — it catches a copy that is the right size but the wrong bytes, and
# it proves the lake is usable from the machine that actually trains.
QC_PROBE = '''r = subprocess.run([sys.executable, "qc/imagery_qc_suite.py", "integrity", "--only", {probe!r},
                    "--outdir", D + "/phase4/qc"], cwd=REPO + "/Scripts", capture_output=True, text=True)
print(r.stdout[-900:])
print("BOOTSTRAP_DONE" if r.returncode == 0 else "QC_SMOKE_FAIL rc=%d" % r.returncode)
'''

QC_LAUNCH = '''# VM QC launch: run the imagery QC suite over the DRIVE copies, detached (survives the
# exec websocket). Auto-generated by pipeline/colab_cli_vmgen.py — do not commit.
import datetime, os, subprocess, time
D = "/content/drive/MyDrive/treedata"
ts = datetime.datetime.now(datetime.timezone.utc).strftime("%Y%m%dT%H%M%SZ")
log = D + "/phase4/logs/imagery_qc_suite_" + ts + ".log"
p = subprocess.Popen("cd /content/repo/Scripts && nohup python -u qc/imagery_qc_suite.py " + {checks!r} +
                     " --workers " + str({workers!r}) + " --outdir " + D + "/phase4/qc"
                     " > " + log + " 2>&1 & echo $!",
                     shell=True, stdout=subprocess.PIPE, text=True)
out, _ = p.communicate(timeout=30)
print("LAUNCHED pid", out.strip())
print("LOG", log)
time.sleep(10)
print("--- first log lines ---")
print(open(log).read()[:1500] if os.path.exists(log) else "(log not flushed yet - read it from Drive)")
'''


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--branch", required=True)
    ap.add_argument("--queue", help="train mode: e.g. queue_A_2024_2017.yaml")
    ap.add_argument("--mode", choices=("train", "qc"), default="train")
    ap.add_argument("--checks", default="all", help="qc mode: suite subcommand (default all)")
    ap.add_argument("--probe", default="2016_snoh", help="qc mode: --only filter for the bootstrap smoke")
    ap.add_argument("--workers", type=int, default=4, help="qc mode: suite --workers")
    ap.add_argument("--outdir", required=True, help="LOCAL dir (session scratchpad) — never the repo or Drive")
    a = ap.parse_args(clean_argv())
    if a.mode == "train" and not a.queue:
        sys.exit("--queue is required in train mode")
    out = pathlib.Path(a.outdir)
    out.mkdir(parents=True, exist_ok=True)
    repo = pathlib.Path(__file__).resolve().parents[2]
    bad = str(out.resolve()).lower()
    if bad.startswith(str(repo).lower()) or bad.startswith(("g:", "\\\\")):
        sys.exit("outdir must be local scratch (not the repo, not Drive) — it will contain a token")
    tok = gh_token()
    if a.mode == "qc":
        head, _, _ = BOOTSTRAP.partition('r = subprocess.run([sys.executable, "phase4_train_queue.py"')
        (out / "vm_bootstrap.py").write_text(
            head.format(branch=a.branch, token=tok, repo_url=REPO_URL) + QC_PROBE.format(probe=a.probe),
            encoding="utf-8")
        (out / "vm_qc.py").write_text(QC_LAUNCH.format(checks=a.checks, workers=a.workers), encoding="utf-8")
        print(f"wrote {out}\\vm_bootstrap.py + vm_qc.py  (QC mode, branch={a.branch}, checks={a.checks}; "
              f"token embedded locally only — delete after the exec)")
        return
    (out / "vm_bootstrap.py").write_text(
        BOOTSTRAP.format(branch=a.branch, token=tok, repo_url=REPO_URL, queue=a.queue), encoding="utf-8")
    (out / "vm_launch.py").write_text(LAUNCH.format(queue=a.queue), encoding="utf-8")
    print(f"wrote {out}\\vm_bootstrap.py + vm_launch.py  (branch={a.branch}, queue={a.queue}; "
          f"token embedded locally only — delete after the exec)")


if __name__ == "__main__":
    main()
