r"""Emit a one-shot VM bootstrap script: rclone-mount the data lake + clone the repo.

Part of Colab runtime autonomy (COLAB_AUTONOMY_SETUP.md). This generator holds NO
secrets — it reads them at run time from D:\edmonds-pipeline\secrets\ and embeds them
into a script written to LOCAL SCRATCH ONLY. Delete the emitted script after use.

Inputs (created once per COLAB_AUTONOMY_SETUP.md):
  secrets/treedata-mount-sa.json   — service-account key (Drive API enabled, folder shared)
  secrets/treedata_folder_id.txt   — the Drive folder id of `treedata` (from its URL)
  gh auth token                    — repo clone token (gh CLI)

Usage:  py -3.12 pipeline/gen_vm_bootstrap.py --session qc [--branch work/...]
Then :  colab exec -s qc -f <printed path> --timeout 900
"""
import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

SECRETS = Path(r"D:\edmonds-pipeline\secrets")
SCRATCH = Path(os.environ.get("LOCALAPPDATA", "")) / "Temp" / "sector_campaign_vm"
MOUNT = "/content/drive/MyDrive/treedata"        # the exact path every script expects


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--session", required=True)
    ap.add_argument("--branch", default="work/20260824-sectors")
    a = ap.parse_args()

    sa_path = SECRETS / "treedata-mount-sa.json"
    fid_path = SECRETS / "treedata_folder_id.txt"
    for p in (sa_path, fid_path):
        if not p.exists():
            sys.exit(f"missing {p} — do the one-time setup in COLAB_AUTONOMY_SETUP.md")
    sa = json.loads(sa_path.read_text(encoding="utf-8"))     # validates it parses
    folder_id = fid_path.read_text(encoding="utf-8").strip()
    tok = subprocess.run(["gh", "auth", "token"], capture_output=True,
                         text=True).stdout.strip()
    if not tok:
        sys.exit("gh auth token returned nothing — `gh auth login` first")

    body = f'''import json, os, subprocess, time
# one-shot VM bootstrap (generated by gen_vm_bootstrap.py — TOKEN-BEARING, scratch only)
SA = {json.dumps(json.dumps(sa))}
FOLDER_ID = {folder_id!r}
BR = {a.branch!r}
AUTH = "https://x-access-token:{tok}@github.com/Kameron-Eck/edmonds-treedata.git"
MOUNT = {MOUNT!r}

subprocess.run("curl -fsSL https://rclone.org/install.sh | bash",
               shell=True, capture_output=True)
open("/content/sa.json", "w").write(SA)
os.makedirs("/root/.config/rclone", exist_ok=True)
open("/root/.config/rclone/rclone.conf", "w").write(
    "[treedata-sa]\\ntype = drive\\nscope = drive\\n"
    "service_account_file = /content/sa.json\\n"
    f"root_folder_id = {{FOLDER_ID}}\\n")
os.makedirs(MOUNT, exist_ok=True)
subprocess.run(["rclone", "mount", "treedata-sa:", MOUNT, "--daemon", "--allow-other",
                "--vfs-cache-mode", "writes", "--vfs-cache-max-size", "40G",
                "--drive-pacer-min-sleep", "10ms", "--transfers", "8"], check=True)
for _ in range(30):                       # wait for the mount to answer
    if os.path.isdir(MOUNT + "/phase4"):
        break
    time.sleep(2)
else:
    raise SystemExit("MOUNT_FAILED: " + MOUNT + " never showed phase4/")
REPO = "/content/repo"
if os.path.exists(REPO):
    subprocess.run(["git", "-C", REPO, "remote", "set-url", "origin", AUTH], check=True)
    subprocess.run(["git", "-C", REPO, "fetch", "--depth", "1", "origin", BR], check=True)
    subprocess.run(["git", "-C", REPO, "checkout", "-B", BR, "FETCH_HEAD"], check=True)
else:
    subprocess.run(["git", "clone", "--depth", "1", "--branch", BR, AUTH, REPO], check=True)
subprocess.run(["git", "-C", REPO, "remote", "set-url", "origin",
                "https://github.com/Kameron-Eck/edmonds-treedata.git"], check=True)
r = subprocess.run(["git", "-C", REPO, "log", "-1", "--oneline"],
                   capture_output=True, text=True)
print("BOOTSTRAP_READY", r.stdout.strip())
'''
    SCRATCH.mkdir(parents=True, exist_ok=True)
    out = SCRATCH / f"vm_bootstrap_{a.session}.py"
    out.write_text(body, encoding="utf-8")
    print(f"emitted {out}  (token+key inside — DELETE after use)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
