r"""Emit a one-shot VM bootstrap script: rclone-mount the data lake + clone the repo.

Part of Colab runtime autonomy (COLAB_AUTONOMY_SETUP.md). This generator holds NO
secrets — it reads them at run time from D:\edmonds-pipeline\secrets\ and embeds them
into a script written to LOCAL SCRATCH ONLY. Delete the emitted script after use.

Inputs (created once per COLAB_AUTONOMY_SETUP.md):
  secrets/treedata-mount-sa.json   — service-account key (Drive API enabled, folder shared)
  secrets/treedata_folder_id.txt   — the Drive folder id of `treedata` (from its URL)
  gh auth token                    — repo clone token (gh CLI)

Usage:  py -3.12 pipeline/gen_vm_bootstrap.py --session qc [--branch work/...]
Then :  colab exec -s qc -f <printed path> --timeout 900
"""
import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

SECRETS = Path(r"D:\edmonds-pipeline\secrets")
SCRATCH = Path(os.environ.get("LOCALAPPDATA", "")) / "Temp" / "sector_campaign_vm"
MOUNT = "/content/drive/MyDrive/treedata"        # the exact path every script expects


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--session", required=True)
    ap.add_argument("--branch", default="work/20260824-sectors")
    a = ap.parse_args()

    sa_path = SECRETS / "treedata-mount-sa.json"
    fid_path = SECRETS / "treedata_folder_id.txt"
    for p in (sa_path, fid_path):
        if not p.exists():
            sys.exit(f"missing {p} — do the one-time setup in COLAB_AUTONOMY_SETUP.md")
    sa = json.loads(sa_path.read_text(encoding="utf-8"))     # validates it parses
    folder_id = fid_path.read_text(encoding="utf-8").strip()
    # WRITER mount: user-OAuth token — files owned by Kam, his quota. The SA has
    # ZERO Drive storage quota, so SA-owned file uploads silently FAIL (measured
    # server-side 2026-08-26; cost one noise campaign). The SA stays for READ and
    # for INDEPENDENT server-side upload verification (write canary v2).
    utok_path = SECRETS / "rclone_user_token.json"
    if not utok_path.exists():
        sys.exit(f'missing {utok_path} — run: rclone authorize "drive" (STATUS 4)')
    utok = json.dumps(json.loads(utok_path.read_text(encoding="utf-8")))
    tok = subprocess.run(["gh", "auth", "token"], capture_output=True,
                         text=True).stdout.strip()
    if not tok:
        sys.exit("gh auth token returned nothing — `gh auth login` first")

    body = f'''import json, os, subprocess, time
# one-shot VM bootstrap (generated by gen_vm_bootstrap.py — TOKEN-BEARING, scratch only)
SA = {json.dumps(json.dumps(sa))}
UTOK = {json.dumps(utok)}
FOLDER_ID = {folder_id!r}
BR = {a.branch!r}
SESSION = {a.session!r}
AUTH = "https://x-access-token:{tok}@github.com/Kameron-Eck/edmonds-treedata.git"
MOUNT = {MOUNT!r}

subprocess.run("curl -fsSL https://rclone.org/install.sh | bash",
               shell=True, capture_output=True)
# fuse3 is NOT preinstalled on Colab images; without fusermount3 the mount dies
# with a bare "daemon exited" (measured 2026-08-26; the canary's root cause).
if subprocess.run(["which", "fusermount3"], capture_output=True).returncode != 0:
    subprocess.run("apt-get install -y -qq fuse3", shell=True, capture_output=True)
open("/content/sa.json", "w").write(SA)
os.makedirs("/root/.config/rclone", exist_ok=True)
open("/root/.config/rclone/rclone.conf", "w").write(
    "[treedata-sa]\\ntype = drive\\nscope = drive\\n"
    "service_account_file = /content/sa.json\\n"
    f"root_folder_id = {{FOLDER_ID}}\\n"
    "[treedata-user]\\ntype = drive\\nscope = drive\\n"
    f"token = {{UTOK}}\\n"
    f"root_folder_id = {{FOLDER_ID}}\\n")
os.makedirs(MOUNT, exist_ok=True)
if os.path.isdir(MOUNT + "/phase4"):
    print("mount already up — skipping (idempotent re-run)")
    r0 = subprocess.CompletedProcess([], 0, "", "")
else:
    r0 = subprocess.run(["rclone", "mount", "treedata-user:", MOUNT, "--daemon",
                     "--vfs-cache-mode", "writes", "--vfs-cache-max-size", "40G",
                     "--drive-pacer-min-sleep", "10ms", "--transfers", "8"],
                    capture_output=True, text=True)
if r0.returncode != 0:
    raise SystemExit("BOOTSTRAP FAIL: rclone mount rc=%d: %s"
                     % (r0.returncode, (r0.stderr or "")[-400:]))
for _ in range(30):                       # wait for the mount to answer
    if os.path.isdir(MOUNT + "/phase4"):
        break
    time.sleep(2)
else:
    raise SystemExit("MOUNT_FAILED: " + MOUNT + " never showed phase4/")
REPO = "/content/repo"
if os.path.exists(REPO):
    subprocess.run(["git", "-C", REPO, "remote", "set-url", "origin", AUTH], check=True)
    subprocess.run(["git", "-C", REPO, "fetch", "--depth", "1", "origin", BR], check=True)
    subprocess.run(["git", "-C", REPO, "checkout", "-B", BR, "FETCH_HEAD"], check=True)
else:
    subprocess.run(["git", "clone", "--depth", "1", "--branch", BR, AUTH, REPO], check=True)
subprocess.run(["git", "-C", REPO, "remote", "set-url", "origin",
                "https://github.com/Kameron-Eck/edmonds-treedata.git"], check=True)
r = subprocess.run(["git", "-C", REPO, "log", "-1", "--oneline"],
                   capture_output=True, text=True)
# WRITE CANARY v2 (STATUS 4): prove uploads actually reach Drive. Write through
# the mount, then stat SERVER-SIDE with the SA credentials — independent of every
# cache involved in the write. The v1 canary read its own vfs cache and was blind.
import hashlib
import time as _t
payload = os.urandom(4 << 20)
cpath = MOUNT + "/phase4/logs/_write_canary.bin"
open(cpath, "wb").write(payload)
want_md5 = hashlib.md5(payload).hexdigest()
ok, q = False, None
for _ in range(24):                      # up to 2 min for the async upload
    # md5sum, not `lsjson --hashes` — the flag doesn't exist on the VM's rclone
    # build (measured 2026-08-26; the flagless canary false-failed a good upload)
    q = subprocess.run(["rclone", "md5sum",
                        "treedata-sa:phase4/logs/_write_canary.bin"],
                       capture_output=True, text=True)
    if q.returncode == 0 and want_md5 in (q.stdout or ""):
        ok = True
        break
    _t.sleep(5)
try:
    os.remove(cpath)
except OSError:
    pass
if not ok:
    raise SystemExit("WRITE_CANARY FAIL: upload never verified server-side via the SA "
                     "— do NOT run writers on this VM. " + ((q.stdout or q.stderr) if q else "")[-200:])
print("WRITE_CANARY PASS (server-side md5 via SA)")
print("BOOTSTRAP_READY", r.stdout.strip())
# Oversight beacon (COLAB_AUTONOMY_SETUP.md "Oversight"): pushes a <2 KB
# phase4/logs/heartbeat_{{session}}.json every 60 s so local `qc/runtime_health.py`
# can check this VM with NO colab exec round-trip. Its own stdout stays on LOCAL
# /content (never another appended file on the mount). Detached: dies with the VM.
subprocess.Popen("cd /content/repo/Scripts/pipeline && nohup python -u vm_heartbeat.py"
                 " --session " + SESSION + " > /content/vm_heartbeat.log 2>&1 &",
                 shell=True)
print("HEARTBEAT_STARTED", SESSION)
'''
    SCRATCH.mkdir(parents=True, exist_ok=True)
    out = SCRATCH / f"vm_bootstrap_{a.session}.py"
    out.write_text(body, encoding="utf-8")
    print(f"emitted {out}  (token+key inside — DELETE after use)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
