r"""Emit a one-shot VM bootstrap script: rclone-mount the data lake + clone the repo.

Part of Colab runtime autonomy (COLAB_AUTONOMY_SETUP.md). This generator holds NO
secrets — it reads them at run time from D:\edmonds-pipeline\secrets\ and embeds them
into a script written to LOCAL SCRATCH ONLY. Delete the emitted script after use.

Inputs (created once per COLAB_AUTONOMY_SETUP.md):
  secrets/treedata-mount-sa.json   — service-account key (Drive API enabled, folder shared)
  secrets/treedata_folder_id.txt   — the Drive folder id of `treedata` (from its URL)
  gh auth token                    — repo clone token (gh CLI)

Usage:  py -3.12 pipeline/gen_vm_bootstrap.py --session qc [--branch work/...]
Then :  colab exec -s qc -f <printed path> --timeout 900
"""
import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

SECRETS = Path(r"D:\edmonds-pipeline\secrets")
SCRATCH = Path(os.environ.get("LOCALAPPDATA", "")) / "Temp" / "sector_campaign_vm"
MOUNT = "/content/drive/MyDrive/treedata"        # the exact path every script expects


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--session", required=True)
    ap.add_argument("--branch", default="work/20260824-sectors")
    a = ap.parse_args()

    sa_path = SECRETS / "treedata-mount-sa.json"
    fid_path = SECRETS / "treedata_folder_id.txt"
    for p in (sa_path, fid_path):
        if not p.exists():
            sys.exit(f"missing {p} — do the one-time setup in COLAB_AUTONOMY_SETUP.md")
    sa = json.loads(sa_path.read_text(encoding="utf-8"))     # validates it parses
    folder_id = fid_path.read_text(encoding="utf-8").strip()
    # WRITER mount: user-OAuth token — files owned by Kam, his quota. The SA has
    # ZERO Drive storage quota, so SA-owned file uploads silently FAIL (measured
    # server-side 2026-08-26; cost one noise campaign). The SA stays for READ and
    # for INDEPENDENT server-side upload verification (write canary v2).
    utok_path = SECRETS / "rclone_user_token.json"
    if not utok_path.exists():
        sys.exit(f'missing {utok_path} — run: rclone authorize "drive" (STATUS 4)')
    utok = json.dumps(json.loads(utok_path.read_text(encoding="utf-8")))
    tok = subprocess.run(["gh", "auth", "token"], capture_output=True,
                         text=True).stdout.strip()
    if not tok:
        sys.exit("gh auth token returned nothing — `gh auth login` first")

    body = f'''import json, os, subprocess, sys, time
# one-shot VM bootstrap (generated by gen_vm_bootstrap.py — TOKEN-BEARING, scratch only)
SA = {json.dumps(json.dumps(sa))}
UTOK = {json.dumps(utok)}
FOLDER_ID = {folder_id!r}
BR = {a.branch!r}
SESSION = {a.session!r}
AUTH = "https://x-access-token:{tok}@github.com/Kameron-Eck/edmonds-treedata.git"
MOUNT = {MOUNT!r}

# ── D14: arm the self-stop watchdog FIRST ─────────────────────────────────
# It used to arm on the LAST line of the bootstrap, so any of the seven
# failure exits below left a live, billing VM with neither watchdog nor
# beacon. Nothing here touches the mount or the network, so it cannot itself
# fail in a way that leaves the VM unmanaged.
_WD = [
    "import subprocess, time, os, json",
    "MOUNT = " + repr(MOUNT),
    "def _dirty_bytes(root='/root/.cache/rclone'):",
    "    # Upload backlog = sum of Size over vfsMeta items with Dirty:true - the same",
    "    # rule vm_heartbeat._vfs_bytes uses. Returns None when unreadable; a caller",
    "    # must NEVER treat None as zero.",
    "    meta = os.path.join(root, 'vfsMeta')",
    "    if not os.path.isdir(meta):",
    "        return None",
    "    tot = 0",
    "    try:",
    "        for dp, _dn, fns in os.walk(meta):",
    "            for f in fns:",
    "                try:",
    "                    with open(os.path.join(dp, f), 'rb') as fh:",
    "                        d = json.loads(fh.read().decode('utf-8', 'replace'))",
    "                    if d.get('Dirty'):",
    "                        tot += int(d.get('Size') or 0)",
    "                except Exception:",
    "                    continue",
    "    except Exception:",
    "        return None",
    "    return tot",
    "def _note(msg):",
    "    # The local watchdog log dies with the VM, so a stop that lost data would be",
    "    # indistinguishable from a clean one. Leave a breadcrumb on the lake.",
    "    try:",
    "        d = os.path.join(MOUNT, 'phase4', 'logs')",
    "        os.makedirs(d, exist_ok=True)",
    "        with open(os.path.join(d, 'selfstop_' + os.environ.get('COLAB_SESSION', 'vm') + '.log'), 'a') as fh:",
    "            fh.write(time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime()) + ' ' + msg + chr(10))",
    "    except Exception:",
    "        pass",
    "def _drain(max_wait=1800):",
    "    # THE DEFECT THIS CLOSES (measured 2026-08-29). The watchdog used a FIXED",
    "    # 300 s sleep then runtime.unassign(). rclone uploads asynchronously, so a",
    "    # queue that had just written a 1.1 GB checkpoint could lose it: the training",
    "    # log reported deploying epoch B24 while Drive still held B7, and the queue's",
    "    # VERIFY:train passed because it only checks size and zip magic. The VM",
    "    # already computes the backlog for its heartbeat; this waits on it.",
    "    t0 = time.time()",
    "    last = None",
    "    d = None",
    "    while time.time() - t0 < max_wait:",
    "        d = _dirty_bytes()",
    "        if d is None:",
    "            print('drain: backlog UNREADABLE - fixed 300 s grace instead', flush=True)",
    "            _note('drain unreadable; fixed 300 s grace')",
    "            time.sleep(300)",
    "            return",
    "        if d == 0:",
    "            el = int(time.time() - t0)",
    "            print('drain: backlog clear after %d s' % el, flush=True)",
    "            _note('drain clear after %d s' % el)",
    "            time.sleep(20)",
    "            return",
    "        if last is None or abs(d - last) > 5_000_000:",
    "            print('drain: %.1f MB pending upload' % (d / 1e6), flush=True)",
    "            last = d",
    "        time.sleep(10)",
    "    mb = (d or 0) / 1e6",
    "    print('drain: TIMED OUT after %d s with %.1f MB pending' % (max_wait, mb), flush=True)",
    "    _note('drain TIMED OUT with %.1f MB pending - ARTIFACTS MAY BE INCOMPLETE' % mb)",
    "def _stop():",
    "    try:",
    "        from google.colab import runtime",
    "        runtime.unassign()",
    "    except Exception as e:",
    "        print('unassign failed:', e)",
    "seen, idle_since, t0 = False, None, time.time()",
    "while True:",
    "    # Scan /proc directly — NOT `pgrep -f`, whose own `/bin/sh -c pgrep -f <pat>`",
    "    # wrapper carries the pattern in its cmdline and so always self-matches,",
    "    # pinning `seen` True forever and making the watchdog never fire",
    "    # (measured 2026-08-27). This scan also skips our own pid.",
    "    q = ''",
    "    for _p in os.listdir('/proc'):",
    "        if not _p.isdigit() or _p == str(os.getpid()):",
    "            continue",
    "        try:",
    "            _c = open('/proc/' + _p + '/cmdline', 'rb').read().decode('utf-8', 'replace')",
    "        except OSError:",
    "            continue",
    "        if 'phase4_train_queue.py' in _c or 'phase4_semantic_finetune.py' in _c:",
    "            q = _p",
    "            break",
    "    if q:",
    "        seen, idle_since = True, None",
    "    elif seen:",
    "        idle_since = idle_since or time.time()",
    "        if time.time() - idle_since > 600:",
    "            _drain()   # wait on the real upload backlog, not a fixed sleep",
    "            _stop()",
    "            break",
    "    elif not os.path.exists('/content/BOOTSTRAP_OK') and time.time() - t0 > 1200:",
    "        # D14: the watchdog is now armed BEFORE the fallible bootstrap steps, so",
    "        # it must distinguish 'bootstrap died' from 'bootstrap fine, queue not up",
    "        # yet'. Seven exits (rclone, fuse3, mount rc, mount never appeared, four",
    "        # git calls, write canary) used to leave a live VM with NO watchdog and NO",
    "        # beacon - invisible to runtime_health, and believed by the operator not to",
    "        # exist. A missing marker after 20 min means the bootstrap never finished.",
    "        print('selfstop: BOOTSTRAP_OK never appeared - bootstrap failed', flush=True)",
    "        _note('stopped: bootstrap never completed')",
    "        _stop()",
    "        break",
    "    elif time.time() - t0 > 7200:   # bootstrapped, but a queue never launched",
    "        _note('stopped: bootstrapped but no queue in 2 h')",
    "        _stop()",
    "        break",
    "    time.sleep(60)",
]
open("/content/vm_selfstop.py", "w").write(chr(10).join(_WD))
# The watchdog names its log after COLAB_SESSION, and a child only inherits the
# environment its parent had AT SPAWN TIME. Setting this below, next to session.txt,
# was too late: the watchdog was already running and had already resolved the name
# to the 'vm' default, so every VM appended to one shared selfstop_vm.log and the
# per-VM identity D12 exists to establish was gone again. Set it BEFORE the spawn.
os.environ["COLAB_SESSION"] = SESSION
subprocess.Popen("nohup python -u /content/vm_selfstop.py > /content/vm_selfstop.log 2>&1 &",
                 shell=True)
print("SELFSTOP_ARMED")

# The installer used to run unchecked, so when it failed the script sailed on and
# died 20 lines later with a bare FileNotFoundError: 'rclone' at the mount call —
# measured on an L4 image 2026-08-29, after the same image class had worked on
# A100. Silence is not success: verify the binary exists, retry, fall back to apt,
# and if it is still missing say so WITH the installer's own output.
def _have(binary):
    return subprocess.run(["which", binary], capture_output=True).returncode == 0

_inst = None
for _attempt, _cmd in enumerate((
        "curl -fsSL https://rclone.org/install.sh | bash",
        "curl -fsSL https://rclone.org/install.sh | bash",   # transient network
        "apt-get install -y -qq rclone")):                   # stale but present
    if _have("rclone"):
        break
    _inst = subprocess.run(_cmd, shell=True, capture_output=True, text=True)
if not _have("rclone"):
    raise SystemExit("BOOTSTRAP FAIL: rclone not installed after 3 attempts. "
                     "last stdout: %s | last stderr: %s"
                     % ((_inst.stdout or "")[-800:] if _inst else "",
                        (_inst.stderr or "")[-800:] if _inst else ""))
print("rclone:", subprocess.run(["rclone", "version"], capture_output=True,
                                text=True).stdout.splitlines()[0]
      if _have("rclone") else "MISSING")
# fuse3 is NOT preinstalled on Colab images; without fusermount3 the mount dies
# with a bare "daemon exited" (measured 2026-08-26; the canary's root cause).
if not _have("fusermount3"):
    subprocess.run("apt-get install -y -qq fuse3", shell=True, capture_output=True)
    if not _have("fusermount3"):
        raise SystemExit("BOOTSTRAP FAIL: fuse3 missing after install; the mount "
                         "would die with a bare 'daemon exited' (2026-08-26 canary)")
# D13 (2026-08-29): publish the session name so artifacts can say WHERE they were
# produced. The VM has no API to ask the Colab CLI what its own session handle is;
# the bootstrap is the only thing that knows, so it hands the name down two ways.
# The FILE is the one that matters: every later `colab exec` is a fresh shell that
# does not inherit this process's environment, so only the children spawned below
# (the beacon, the self-stop watchdog) see the env var. On LOCAL disk, deliberately
# — it describes this VM, not the shared lake.
open("/content/session.txt", "w").write(SESSION)
# COLAB_SESSION is already set above, before the watchdog spawn - it has to be, or
# the watchdog inherits nothing. Left here as a no-op for the beacon spawned below.
open("/content/sa.json", "w").write(SA)
os.makedirs("/root/.config/rclone", exist_ok=True)
open("/root/.config/rclone/rclone.conf", "w").write(
    "[treedata-sa]\\ntype = drive\\nscope = drive\\n"
    "service_account_file = /content/sa.json\\n"
    f"root_folder_id = {{FOLDER_ID}}\\n"
    "[treedata-user]\\ntype = drive\\nscope = drive\\n"
    f"token = {{UTOK}}\\n"
    f"root_folder_id = {{FOLDER_ID}}\\n")
os.makedirs(MOUNT, exist_ok=True)
if os.path.isdir(MOUNT + "/phase4"):
    print("mount already up — skipping (idempotent re-run)")
    r0 = subprocess.CompletedProcess([], 0, "", "")
else:
    r0 = subprocess.run(["rclone", "mount", "treedata-user:", MOUNT, "--daemon",
                     "--vfs-cache-mode", "writes", "--vfs-cache-max-size", "40G",
                     "--drive-pacer-min-sleep", "10ms", "--transfers", "8"],
                    capture_output=True, text=True)
if r0.returncode != 0:
    raise SystemExit("BOOTSTRAP FAIL: rclone mount rc=%d: %s"
                     % (r0.returncode, (r0.stderr or "")[-400:]))
for _ in range(30):                       # wait for the mount to answer
    if os.path.isdir(MOUNT + "/phase4"):
        break
    time.sleep(2)
else:
    raise SystemExit("MOUNT_FAILED: " + MOUNT + " never showed phase4/")
REPO = "/content/repo"
if os.path.exists(REPO):
    subprocess.run(["git", "-C", REPO, "remote", "set-url", "origin", AUTH], check=True)
    subprocess.run(["git", "-C", REPO, "fetch", "--depth", "1", "origin", BR], check=True)
    subprocess.run(["git", "-C", REPO, "checkout", "-B", BR, "FETCH_HEAD"], check=True)
else:
    subprocess.run(["git", "clone", "--depth", "1", "--branch", BR, AUTH, REPO], check=True)
subprocess.run(["git", "-C", REPO, "remote", "set-url", "origin",
                "https://github.com/Kameron-Eck/edmonds-treedata.git"], check=True)
r = subprocess.run(["git", "-C", REPO, "log", "-1", "--oneline"],
                   capture_output=True, text=True)
# WRITE CANARY v2 (STATUS 4): prove uploads actually reach Drive. Write through
# the mount, then stat SERVER-SIDE with the SA credentials — independent of every
# cache involved in the write. The v1 canary read its own vfs cache and was blind.
import hashlib
import time as _t
payload = os.urandom(4 << 20)
cpath = MOUNT + "/phase4/logs/_write_canary.bin"
open(cpath, "wb").write(payload)
want_md5 = hashlib.md5(payload).hexdigest()
ok, q = False, None
for _ in range(24):                      # up to 2 min for the async upload
    # md5sum, not `lsjson --hashes` — the flag doesn't exist on the VM's rclone
    # build (measured 2026-08-26; the flagless canary false-failed a good upload)
    q = subprocess.run(["rclone", "md5sum",
                        "treedata-sa:phase4/logs/_write_canary.bin"],
                       capture_output=True, text=True)
    if q.returncode == 0 and want_md5 in (q.stdout or ""):
        ok = True
        break
    _t.sleep(5)
try:
    os.remove(cpath)
except OSError:
    pass
if not ok:
    raise SystemExit("WRITE_CANARY FAIL: upload never verified server-side via the SA "
                     "— do NOT run writers on this VM. " + ((q.stdout or q.stderr) if q else "")[-200:])
print("WRITE_CANARY PASS (server-side md5 via SA)")
# Editable install (refactor Stage 3): phase4seg + shared modules resolve on the VM the
# same way they do locally and in CI, with no sys.path hacks. -q keeps the log readable;
# failure is FATAL — a VM without the install runs scripts whose imports half-resolve.
ir = subprocess.run([sys.executable, "-m", "pip", "install", "-q", "-e", "/content/repo"],
                    capture_output=True, text=True)
if ir.returncode != 0:
    raise SystemExit("EDITABLE_INSTALL FAIL: " + (ir.stderr or ir.stdout)[-300:])
print("EDITABLE_INSTALL OK")
open("/content/BOOTSTRAP_OK", "w").write("1")   # D14: tells the watchdog
print("BOOTSTRAP_READY", r.stdout.strip())
# Oversight beacon (COLAB_AUTONOMY_SETUP.md "Oversight"): pushes a <2 KB
# phase4/logs/heartbeat_{{session}}.json every 60 s so local `qc/runtime_health.py`
# can check this VM with NO colab exec round-trip. Its own stdout stays on LOCAL
# /content (never another appended file on the mount). Detached: dies with the VM.
subprocess.Popen("cd /content/repo/Scripts/pipeline && nohup python -u vm_heartbeat.py"
                 " --session " + SESSION + " > /content/vm_heartbeat.log 2>&1 &",
                 shell=True)
print("HEARTBEAT_STARTED", SESSION)
# SELF-STOP WATCHDOG (2026-08-27): the CLI can lose its session handle (404/401
# on long-lived VMs) leaving no external way to stop the runtime — a frozen VM
# then bills until Google reclaims it. The VM ends ITSELF: once a queue/engine
# process has been seen, 10 idle minutes + a 5-min upload-drain grace triggers
# runtime.unassign(); a VM that never sees a queue self-stops after 2 h.

'''
    SCRATCH.mkdir(parents=True, exist_ok=True)
    out = SCRATCH / f"vm_bootstrap_{a.session}.py"
    out.write_text(body, encoding="utf-8")
    print(f"emitted {out}  (token+key inside — DELETE after use)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
